"""add user profile fields

Revision ID: 028261a45bd7
Revises: 4cd0fd748120
Create Date: 2026-09-25 21:21:11.013059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '028261a45bd7'
down_revision: Union[str, Sequence[str], None] = '4cd0fd748120'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('display_name', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('avatar_uploaded', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('avatar_version', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_version')
    op.drop_column('users', 'avatar_uploaded')
    op.drop_column('users', 'display_name')
    # ### end Alembic commands ###
