"""updated task collections

Revision ID: 4cd0fd748120
Revises: ca304a973e7a
Create Date: 2026-09-20 14:12:51.654009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cd0fd748120'
down_revision: Union[str, Sequence[str], None] = 'ca304a973e7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_collections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_user_task_collection_name')
    )
    op.create_index(op.f('ix_task_collections_user_id'), 'task_collections', ['user_id'], unique=False)
    op.create_table('collection_task_links',
    sa.Column('collection_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['task_collections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('collection_id', 'task_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('collection_task_links')
    op.drop_index(op.f('ix_task_collections_user_id'), table_name='task_collections')
    op.drop_table('task_collections')
    # ### end Alembic commands ###
