"""add cascade deletes

Revision ID: 5516ac738f40
Revises: ddbd73a645f1
Create Date: 2026-09-07 02:18:18.036732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5516ac738f40'
down_revision: Union[str, Sequence[str], None] = 'ddbd73a645f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('daily_activities_user_id_fkey'), 'daily_activities', type_='foreignkey')
    op.create_foreign_key(None, 'daily_activities', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('deadline_task_completions_task_id_fkey'), 'deadline_task_completions', type_='foreignkey')
    op.create_foreign_key(None, 'deadline_task_completions', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('recurring_task_progress_task_id_fkey'), 'recurring_task_progress', type_='foreignkey')
    op.create_foreign_key(None, 'recurring_task_progress', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('task_active_periods_task_id_fkey'), 'task_active_periods', type_='foreignkey')
    op.create_foreign_key(None, 'task_active_periods', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('tasks_user_id_fkey'), 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key(op.f('tasks_user_id_fkey'), 'tasks', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'task_active_periods', type_='foreignkey')
    op.create_foreign_key(op.f('task_active_periods_task_id_fkey'), 'task_active_periods', 'tasks', ['task_id'], ['id'])
    op.drop_constraint(None, 'recurring_task_progress', type_='foreignkey')
    op.create_foreign_key(op.f('recurring_task_progress_task_id_fkey'), 'recurring_task_progress', 'tasks', ['task_id'], ['id'])
    op.drop_constraint(None, 'deadline_task_completions', type_='foreignkey')
    op.create_foreign_key(op.f('deadline_task_completions_task_id_fkey'), 'deadline_task_completions', 'tasks', ['task_id'], ['id'])
    op.drop_constraint(None, 'daily_activities', type_='foreignkey')
    op.create_foreign_key(op.f('daily_activities_user_id_fkey'), 'daily_activities', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
