"""add user timezone and deadline complition date

Revision ID: 567f06d0374b
Revises: ec447355e776
Create Date: 2026-09-17 13:23:04.463276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '567f06d0374b'
down_revision: Union[str, Sequence[str], None] = 'ec447355e776'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deadline_task_completions', sa.Column('completion_date', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('timezone', sa.String(length=64), server_default='UTC', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'timezone')
    op.drop_column('deadline_task_completions', 'completion_date')
    # ### end Alembic commands ###
